[workspace]
resolver = "2"
members = ["crates/zastava-core", "crates/zastava-proxy", "crates/zastava-cli"]
exclude = ["spike"]

[workspace.package]
version = "0.1.0-dev"
edition = "2021"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/gorka2354/zastava"
authors = ["gorka2354"]

[workspace.dependencies]
zastava-core = { path = "crates/zastava-core" }
zastava-proxy = { path = "crates/zastava-proxy" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dirs = "6"
